@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": true,
    "cutInterfaceStructures": true,
    "cutDataStructures": true,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "edu.ics372.abdnn.medsched.interfaces.Resource",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_1194001131 { 
   	label=ics372
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_45482166 { 
   	label=abdnn
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   AnonymousEntity1769287098[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AnonymousEntity</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

AppointmentRequest1453701551[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)AppointmentRequest</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   department: Department [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   patient: Patient [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   provider: Provider [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   scheduleDate: ScheduleDate [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DateTimesSlots290082825[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DateTimesSlots</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   dateTimeSlots: Bag&lt;ScheduleDate&gt; [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ add(scheduleDate: ScheduleDate)</TD></TR>
<TR><TD ALIGN="LEFT" >+ filter(predicate: Predicate&lt;ScheduleDate&gt;): Iterator&lt;ScheduleDate&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ iterator(): Iterator&lt;ScheduleDate&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ pop(scheduleDate: ScheduleDate): ScheduleDate</TD></TR>
<TR><TD ALIGN="LEFT" >+ remove(scheduleDate: ScheduleDate)</TD></TR>
<TR><TD ALIGN="LEFT" >+ size(): int</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Duration175708808[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Duration</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   end: LocalTime [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   start: LocalTime [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ sameTimes(timeslot: Duration): boolean</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

DurationLock175708808[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)DurationLock</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   date: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >#   duration: Duration [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Entity1769287098[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Entity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: int [1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Location1769287098[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Location</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Meeting1769287098[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Meeting</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   host: Person [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   location: Location [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   scheduleDate: ScheduleDate [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

NamedEntity1769287098[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)NamedEntity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   name: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Person1769287098[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Person</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   appointments: ArrayList&lt;ScheduleDate&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   lastname: String [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Resource1769287098[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Resource</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   availabilty: Availabilty [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   durationLock: DurationLock [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ book(date: Date, duration: Duration)</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

ScheduleDate175708808[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)ScheduleDate</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   date: Date [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   timeslots: ArrayList&lt;Timeslot&gt; [0..*]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

Timeslot175708808[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)Timeslot</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   duration: Duration [0..1]</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
AnonymousEntity1769287098 -> AppointmentRequest1453701551[arrowhead=none, arrowtail=empty, dir=both];
AnonymousEntity1769287098 -> Duration175708808[arrowhead=none, arrowtail=empty, dir=both];
AnonymousEntity1769287098 -> Entity1769287098[arrowhead=none, arrowtail=empty, dir=both];
AppointmentRequest1453701551 -> ScheduleDate175708808[label="scheduleDate
[0..1]"];
DateTimesSlots290082825 -> ScheduleDate175708808[label="dateTimeSlots
[0..1]"];
Entity1769287098 -> ScheduleDate175708808[arrowhead=none, arrowtail=empty, dir=both];
Meeting1769287098 -> ScheduleDate175708808[label="scheduleDate
[0..1]"];
NamedEntity1769287098 -> Resource1769287098[arrowhead=none, arrowtail=empty, dir=both];
Person1769287098 -> ScheduleDate175708808[label="appointments
[0..*]"];
Resource1769287098 -> Duration175708808[label="book() -> sameTimes()"];
Resource1769287098 -> DurationLock175708808[label="durationLock
[0..1]"];
Resource1769287098 -> Location1769287098[arrowhead=none, arrowtail=empty, dir=both];
Resource1769287098 -> Meeting1769287098[arrowhead=none, arrowtail=empty, dir=both];
Resource1769287098 -> Person1769287098[arrowhead=none, arrowtail=empty, dir=both];
Resource1769287098 -> Timeslot175708808[arrowhead=none, arrowtail=empty, dir=both];
ScheduleDate175708808 -> Timeslot175708808[label="timeslots
[0..*]"];
Timeslot175708808 -> Duration175708808[label="duration
[0..1]"];
    
}
@enduml